### ISSUE TITLE
Migrate to different hosting

### ISSUE THREAD

**Issue by Philippus** [spray/sbt-revolver#100]
On May 1st Bintray will be sunset (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Do you already have plans to move sbt-revolver somewhere else?

The brownouts mentioned on that page have already started I think.

**Comment by raboof** [comment]
Work is already underway to migrate existing artifacts under https://repo.scala-sbt.org to a new place sbt-wide ( https://github.com/sbt/sbt/issues/6294 ).

For new releases, I imagine we would update or release procedure to publish to that new place.

**Comment by mkurz** [comment]
See #112 - relying solelyon repo.scala-sbt.org might cause troubles in the future.

**Comment by jrudolph** [comment]
Probably best will be to create a 0.10.0 without any substantial changes and publish that to maven central.

**Comment by jrudolph** [comment]
0.10.0 is on its way to Maven Central.
