### ISSUE TITLE
Huge CPU usage

### ISSUE THREAD

**Issue by evbo** [spray/sbt-revolver#106]
Hi,

I am using hot reloading provided by webpack and then sbt-revolver to watch for changes in my Scala.JS source. I've tried to mitigate obvious sources of slowdown, by limiting polling and ensuring nothing in the `target` folder is watched (since there are tons of npm modules):

```scala
    // during hot reloading poll for changes every 5 seconds
    pollInterval := 5.seconds,
    // do not reload due to changes within less than 10 seconds
    watchAntiEntropy := 10.seconds,
    // do not watch the target directory as the many node packages will slow the CPU down
    watchSources := watchSources.value.filterNot(_.base.getPath.contains("target")),
```

**Are there are any other settings to more aggressively limit cpu-intensive operations during a hot reload?**

Would simply turning off all file watching be cheap fix? How to do that?

I run scalajs bundler and the underlying webpack dev server like:

`fullOptJS::startWebpackDevServer; ~fullOptJS::webpack`

I have no root cause for why, but _seemingly randomly_ after several hot reloads the CPU usage eventually spikes to the point where my mouse cursor can barely even move while doing a reload!

I have a modest CPU but it holds up fine usually. It's just after running revolver with `~` that after a while it might act up:
> lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           60
Model name:                      Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz

**Comment by raboof** [comment]
Hmm, hard to say. One think I'd try is checking with `visualvm` whether it is sbt 'itself' using a lot of CPU, or perhaps memory is filling up and it's actually the garbage collector.

**Comment by evbo** [comment]
Thanks, so if there's no other ways to limit CPU usage than I've already tried I will close

**Comment by evbo** [comment]
@raboof while not helpful in identifying root cause, I've found docker's `cpus` setting to be especially helpful in this case; I just run all my builds in a container with it set to fewer than number of cpus I own. Works like a charm and very simple so long as you're willing to use Docker
