### ISSUE TITLE
Artefacts not available on Sonatype

### ISSUE THREAD

**Issue by jmvandebron** [spray/sbt-revolver#110]
Hi, we are having trouble adding the sbt-revolver plugin to our sbt build, because the latest version (0.9.1) cannot be found.

Can you tell us if/when this plugin will be migrated to Sonatype (https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html)?

**Comment by jrudolph** [comment]
As most sbt plugins it is available at the sbt plugin repo at https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases:

https://scala.jfrog.io/ui/native/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/

What is the error message you are getting?

**Comment by jmvandebron** [comment]
I've been unable to reproduce the issue lately, and have not saved the logs from when we had the issues (should have done that :( ). Perhaps this was caused by some misconfiguration at my clients' side. 
Anyway, this issue can be closed.
