### ISSUE TITLE
Is there an alternative?

### ISSUE THREAD

**Issue by dejvid** [spray/sbt-revolver#111]
Is there an up to data version of this plugin? Or something similar? Looks like developement has stopped. Are there alternatives for this plugin? Or was it replaces with something else? Looks like really cool plugin. Please let us know :)

**Comment by sirthias** [comment]
sbt-revolver is working nicely also with the current SBT versions.
Is there sth that doesn't work for you?

**Comment by eltimn** [comment]
sbt-revolver doesn't seem to be published anywhere, at least not where sbt is expecting it at https://repo1.maven.org/maven2/io/spray/sbt-revolver_2.12_1.0/0.9.1/sbt-revolver-0.9.1.pom

Do you know if it is published somewhere else?

**Comment by raboof** [comment]
> Do you know if it is published somewhere else?

Yes, it is published to https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases (and sbt will normally find it there), but this repo is currently down. You can track this at https://github.com/sbt/sbt/issues/7202
