### ISSUE TITLE
javaOptions in Revolver.reStart doesn't use the provided args

### ISSUE THREAD

**Issue by taylorleese** [spray/sbt-revolver#35]
I noticed that my arguments aren't respected when using:

```scala
javaOptions in Revolver.reStart ++= myArgs
```

When I ```ps -ef | grep java``` to see the background process running it didn't use the provided arguments.

**Comment by jrudolph** [comment]
This may have been fixed by now (at least the work around seems to work). Please reopen if you have a similar issue.
