### ISSUE TITLE
How can I make this work with IntelliJ 14?

### ISSUE THREAD

**Issue by drozzy** [spray/sbt-revolver#41]
How do I make this work with IntelliJ?
I have a spray project, but I currently have to restart it every time I make a change to source.

**Comment by danielwegener** [comment]
Assuming you have added revolver to your plugins.sbt and build.sbt, just open the terminal screen in IntelliJ and run `sbt ~re-start` in your project directory.
If you want to use debugging, try the `Revolver.enableDebugging(port = 5005, suspend = true)` setting and create a matching Remote Debug Configuration in IntelliJ.
