### ISSUE TITLE
How to filter restart to exclude some sources/resources ?

### ISSUE THREAD

**Issue by labe-me** [spray/sbt-revolver#43]
Hello,

I would like to add a filter to exclude some sources so sbt-revolver won't restart if only one of these files is modified. 

Is there some way to do that without removing the file from sbt sources (which is required by another packaging task) ?

**Comment by sirthias** [comment]
Laurent,
this question is more an SBT usage question rather than an sbt-revolver ticket.
What you want is to change the `watch-sources` setting of SBT.
See [this page](http://www.scala-sbt.org/0.12.2/docs/Howto/triggered.html) for more info.

**Comment by labe-me** [comment]
Thank you for the reply.

Actually I'd like my .less file to be compiled to .css on file save but not to restart the app which will happily serve the new .css when it will be ready (same goes for other kind of static resources, adding an image to the resource folder shouldn't restart the server).

That's why a filter or something of this sort could be handy to tell sbt-revolver when to restart the app, when to only run compile tasks, when to do nothing, etc.

My knowledge of sbt is quite superficial so maybe there's already a way to do this?

Best
Laurent
