### ISSUE TITLE
reStart does not include "provided" dependencies by default

### ISSUE THREAD

**Issue by vn971** [spray/sbt-revolver#44]
reStart does not include `Provided` dependencies by default. This leads to ClassNotFoundException-s for a project that uses "provided" scope.

Since we know that `sbt-revolver` will launch the app without any container, wouldn't it be wise to take the `Compile` classpath by default?

Current work-around I do for my project now:
`fullClasspath in reStart <<= fullClasspath in Compile`

The Revolver plugin could do it by default on the following line:
https://github.com/spray/sbt-revolver/blob/master/src/main/scala/spray/revolver/RevolverPlugin.scala#L32
Do you know any objections/downsides for such a change? I can send a PR of course.

**Comment by MikaelMayer** [comment]
I have the same problem, but vn971's workaround was not working for me.
Basically, if I do the command `subproject/run`, then it works, but i I do `re-start`, it fails saying that the scala library cannot be found (even though it launches the same session).

**Comment by vn971** [comment]
Hmm. If your application cannot find the Scala library, then it seems you have a different issue. This issue is about "Provided" scope only.

**Comment by MikaelMayer** [comment]
OK I'll launch a new thread. What is the "Provided" scope?

**Comment by jrudolph** [comment]
sbt-revolver mimics the behavior of `run` which also doesn't include libraries from the provided scope. Is there any reason I am missing why we should change that?

In any case, you can always adapt `fullClasspath in reStart` if you need custom behavior or you can also just put the `provided` dependency in `runtime` scope if that's what you are after.

**Comment by MikaelMayer** [comment]
My problem comes from some kind of reflection:
In the new thread #51 I explain this (you saw it)

Since I am dealing with a sub-project (scala-js with spray), what I tried to do is the following (in `build.sbt` at the root level)

    .jvmSettings(
        Revolver.settings:_*
    )
    .jvmSettings(
        fullClasspath in Revolver.reStart <<= fullClasspath in Runtime,
    )

But this does not solve the problem of #51. Same if I replace the second line by this in the `build.sbt` at the root level.

    .jvmSettings(
        fullClasspath in Revolver.reStart <<= fullClasspath in Compile,
    )

Is there any other variables I can try to change? Even debugging with `.jvmSettings(Revolver.enableDebugging(port = 9999, suspend = true))` prevent the application to start.

**Comment by jrudolph** [comment]
@MikaelMayer can we discuss your issue in #51 (I already commented)? It doesn't seem related to this one.

**Comment by jrudolph** [comment]
I'm closing this as I currently don't see a reason why I should change the default behavior which mimics what `run` does. If you can show that `re-start` works differently than `run`, please reopen, so we can reconsider options.
