### ISSUE TITLE
option to use Fork.java instead of Fork.scala

### ISSUE THREAD

**Issue by yanns** [spray/sbt-revolver#46]
It would fix https://github.com/kamon-io/Kamon/issues/77 for example

**Comment by jrudolph** [comment]
@yanns yes, that probably makes sense. It will reduce round-trip time a bit, though, because the whole scala-library.jar will then have to be verified at every start. Maybe we can make it configurable.

**Comment by yanns** [comment]
@jrudolph yes a configuration would be the better option I think.

**Comment by yanns** [comment]
https://github.com/spray/sbt-revolver/pull/47

**Comment by jrudolph** [comment]
The upcoming version 0.8.0-RC1 will use Fork.java by default.
