### ISSUE TITLE
reStart confusing command name

### ISSUE THREAD

**Issue by MasseGuillaume** [spray/sbt-revolver#48]
`reStart` and all commands should be renamed some something less confusing like: `revStart` or `revolver-start`

**Comment by jrudolph** [comment]
We like this name and you are the first to complain :) Actually, it's older than the name "revolver" and captures its semantics of stopping and starting the process anew quite well.

As changing the name will confuse more people than it is helping we would need a few more votes before considering a name change. So, I'm closing this for now.

**Comment by MasseGuillaume** [comment]
sbt has `addCommandAlias` maybe this can solve this issue in a non destructive way. I will add this on my end.

This issue arises from a pair programming session. Logically, behing the first one to report the issue does not make my claim invalid. I agree with you, changing the ui is really confusing. I'm just adding this comment to hightlight a workarround.
