### ISSUE TITLE
Make sbt-revolver an AutoPlugin

### ISSUE THREAD

**Issue by hseeberger** [spray/sbt-revolver#50]

**Comment by jrudolph** [comment]
It will be starting from the upcoming 0.8.0-RC1.

**Comment by hseeberger** [comment]
Yay! When will 0.8.0-RC1 be released?

**Comment by jrudolph** [comment]
I already released it to [bintray](https://bintray.com/jrudolph/sbt-plugins/sbt-revolver/0.8.0-RC1/view) but I just asked for inclusion into sbt-plugin-releases. So, for now you could give it a try by adding a custom resolver

```scala
resolvers += Resolver.url("jrudolph-sbt-plugins", url("https://bintray.com/jrudolph/sbt-plugins"))(Resolver.ivyStylePatterns)
```

**Comment by jrudolph** [comment]
Actually, for some reason the redirection to `dl.bintray.com` does not work automatically, so, you need to make it

```scala
resolvers += Resolver.url("jrudolph-sbt-plugins", url("https://dl.bintray.com/jrudolph/sbt-plugins"))(Resolver.ivyStylePatterns)
```

**Comment by hseeberger** [comment]
Thanks!
