### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by jrudolph** [spray/sbt-revolver#53]
0.8.0-RC1 is already at https://bintray.com/jrudolph/sbt-plugins/ but the artifact is still waiting to be included into sbt-plugin-releases.

 - [x] wait for repository to be included in sbt-plugin-releases
 - [x] announce RC1
 - [x] reinstate 0.8.0 changes to README that were reverted
 - [x] proof read README

**Comment by jrudolph** [comment]
@eed3si9n any idea what's the hold up there? I applied for inclusion into sbt-plugin-releases almost two months ago? Did the process change?

**Comment by eed3si9n** [comment]
Sorry about that. I am not sure if I ever got the notification.
I just linked it manually.

**Comment by jrudolph** [comment]
Excellent, thanks Eugene!

**Comment by jrudolph** [comment]
Shouldn't the plugin now turn up at https://dl.bintray.com/sbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.10/sbt_0.13/ (like at https://dl.bintray.com/jrudolph/sbt-plugins/io.spray/sbt-revolver/scala_2.10/sbt_0.13/)? 

`sbt-plugin-releases`  contains older versions of sbt-revoler so I wonder if they were somehow manually imported from an older sbt-plugin which now blocks new artifacts from jrudolph/sbt-plugins turning up? Or, am I missing something else?

**Comment by eed3si9n** [comment]
> Shouldn't the plugin now turn up at https://dl.bintray.com/sbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.10/sbt_0.13/ (like at https://dl.bintray.com/jrudolph/sbt-plugins/io.spray/sbt-revolver/scala_2.10/sbt_0.13/)?

It might take some time to sync. Contact Bintray support if it doesn't sync in an hour I guess.

**Comment by jrudolph** [comment]
Since that didn't work I wrote to Bintray support. Here's their response:

> The issue appears to be a wrong path prefix that was defined while linking this package from your repo to the sbt-plugin-releases repository. The GH thread says this package was included manually, it's possible that the person who linked this package had entered a wrong path prefix. The path prefix for the inclusion has to correspond to the deployment path of the included package. In this case, your package is deployed to your own repository under:
/io.spray/sbt-revolver/scala_2.10  
>
> The path prefix that was defined is just "sbt", while the correct path prefix is mentioned above. This will certainly prevent your version from being synced to the sbt-plugins-releases repo.You'll need to unlink this package and request for it to be included again with the correct path, or reach out to SBT and have them unlink and link this package with the correct path prefix, which is "io.spray/sbt-revolver/scala_2.10"

Is that something that you could fix, @eed3si9n?

**Comment by eed3si9n** [comment]
Bintray support person was right. I unlinked and linked it back again with a blank path prefix, and now it seems to be working: https://dl.bintray.com/sbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.10/sbt_0.13/

**Comment by jrudolph** [comment]
Great, thanks again, Eugene!

**Comment by jrudolph** [comment]
A few people already used 0.8.0-RC1 without any issues reported. I therefore released 0.8.0 without further changes.
