### ISSUE TITLE
autoplugin vs `Revolver.settings`?

### ISSUE THREAD

**Issue by refried** [spray/sbt-revolver#54]
README.md says revolver 0.7.2 is an AutoPlugin, and that no additional config is necessary, but it actually [*isn't*](https://github.com/spray/sbt-revolver/blob/v0.7.2/src/main/scala/spray/revolver/RevolverPlugin.scala#L22) an AutoPlugin, and additional config *is* necessary (`Revolver.settings`)

Do you want to fix the README to describe the released vs snapshot instructions separately, or do you want to release an AutoPlugin version, or what.

Cheers

**Comment by jrudolph** [comment]
Thanks, @refried, you are right, the repository has currently already partly advanced to the upcoming 0.8.0 version. I reverted the README for now.

**Comment by refried** [comment]
:+1:
