### ISSUE TITLE
Are sbt-revolver configuration README.md examples correct after recent autoplugin changes?

### ISSUE THREAD

**Issue by LeeTibbert** [spray/sbt-revolver#59]
Could someone in the know take a look at the sbt-revolver configuration examples in
the light of recent autoplugin changes?  
Specifically the example

`mainClass in Revolver.reStart := Some("com.example.Main")`

Using sbt-revolver 0.8.0, sbt 0.13.11 & scala 2.11.7, that example failed in
my build.sbt with a complaint about reStart not being a member of Revolver.
(I believe/suspect that Revolver became RevolverPlugin, along
with other changes, during the autoplugin transformation.)

After much thrashing, I found that the following code line worked
for me as described. 

`mainClass in reStart := Some("yyy.zzz.SubmitToSpark")`

I apologize in advance if there is some obvious sbt wizardry I missed.
I am probably neither the first nor the last to note that sbt has a __step__
learning curve.

Most importantly, thank you for sbt-revolver. It is saving me time already.

**Comment by jrudolph** [comment]
Thanks, @LeeTibbert. Very good point. We need to go through all the code examples and see if they still work or fix them otherwise.
