### ISSUE TITLE
Is it possible to add configuration to ignore file changes from certain directly or with certain file path pattern?

### ISSUE THREAD

**Issue by cheeven** [spray/sbt-revolver#61]
Hello,

I am writing a small akka-http application that will also serve some simple static file to the front end as-is. Is it possible to add a SBT configuration in your plugin so that it does not restart the process for those file changes? If it can be set to ignore file changes based on folder locations or file path patterns, it will be very useful. 

FYI - it is an idea based on nodemon (an app to restart NodeJS application automatically) and its "ignore" flag.

Many thanks.
Cheeven

**Comment by jrudolph** [comment]
We just use the `~` operator from sbt so you should be able to customize
its behavior by adapting the watchSources setting.
Am 16.05.2016 12:04 schrieb "Cheeven Tsai" <notifications@github.com>:

**Comment by cheeven** [comment]
Ah. I see.

Thanks a lot!

**Comment by jrudolph** [comment]
Added a pointer to the sbt documentation to the README for whoever will encounter this problem next.
