### ISSUE TITLE
Publish revolver for sbt 1.0.0

### ISSUE THREAD

**Issue by jozi-k** [spray/sbt-revolver#62]
As new version of sbt (and also winter) is coming, do you consider publishing revolver for milestones (currently for 1.0.0-M4)?

**Comment by antonkulaga** [comment]
Yes, it will be great to see it there

**Comment by povder** [comment]
sbt 1.0.0 final has been released

**Comment by jrudolph** [comment]
We just published 0.9.0 cross-built for sbt 0.13.x and sbt 1.0.x.
