### ISSUE TITLE
reForkOptions should include envVars

### ISSUE THREAD

**Issue by danxmoran** [spray/sbt-revolver#63]
SBT's default [`forkOptions`](https://github.com/sbt/sbt/blob/c903e7ca2840d77582774332211c1612a0520d1b/main/src/main/scala/sbt/Defaults.scala#L494) uses the value of the `envVars` task when building a `ForkOptions` object, but [`reForkOptions`](https://github.com/spray/sbt-revolver/blob/master/src/main/scala/spray/revolver/RevolverPlugin.scala#L76) doesn't. This can cause some really confusing discrepancies between the behavior of `run` and `reStart`.

It should be an easy fix, so I'll set up a PR for it.

**Comment by jrudolph** [comment]
Absolutely, thanks for looking into this.
