### ISSUE TITLE
Specify project to enable Revolver

### ISSUE THREAD

**Issue by ctataryn** [spray/sbt-revolver#66]
> sbt-revolver is an auto plugin, so you don't need any additional configuration in your build.sbt nor in Build.scala to make it work. **In multi-module builds it will be enabled for each module**.

Is it possible, in a multi-module build to enable Revolver for just one project instead of all?

**Comment by fdietze** [comment]
The only thing I found is:
```
disablePlugins(RevolverPlugin)
```

you can do this on the root project as well as on subprojects.

**Comment by landlockedsurfer** [comment]
I struggled to get `~re-start` to work with a multi-project setup (no automatic restart was performed after code changes), but after using
```
disablePlugins(RevolverPlugin)
```
things are working nicely. Thanks for posting this!

**Comment by jonasanso** [comment]
Hi @landlockedsurfer 

I am trying to use the approach you proposed without success. 
In my case re-start does not even start the server. 

Is your project public? I would like to take a look and see how it works.

**Comment by manfredweber** [comment]
Hi @jonasanso, unfortunately our project is not on Github. Is your project on Github? We might be able to work out the problem together.

**Comment by landlockedsurfer** [comment]
Hi @jonasanso, unfortunately our project is not on Github. Is your project on Github? We might be able to work out the problem together.

**Comment by jonasanso** [comment]
Thanks @manfredweber. As expected it was my fault. I was just missing the ~  😄

**Comment by landlockedsurfer** [comment]
Sounds great! Using sbt-revolver turned out to be a huge timesaver for me.

**Comment by jrudolph** [comment]
Great you found a solution and thanks for helping out everyone. I just added a note to the README clarifying how to disable the plugin for just some submodules.
