### ISSUE TITLE
Compile sbt-revolver for scala 2.12.x

### ISSUE THREAD

**Issue by bdupharm** [spray/sbt-revolver#69]
Looking at https://dl.bintray.com/sbt/sbt-plugin-releases/io.spray/sbt-revolver/ I see that `sbt-revolver` is only compiled for scala versions up to `2.10.x`. 

Had to specify the scala version in my project like this to get sbt to resolve the plugin path correctly:
```
 libraryDependencies += sbtPluginExtra(
     m = "io.spray" % "sbt-revolver" % "0.8.0",
     sbtV = "0.13",
     scalaV = "2.10"
 )
```

**Comment by jrudolph** [comment]
Hi @bdupharm,

as sbt-revolver is an sbt plugin we need to be compatible with the current sbt version. The latest version is compatible with sbt 0.13.x which is built with Scala 2.10.

However, this doesn't mean that you cannot *use* sbt-revolver with any kind of project regardless of the Scala version used as long as the project uses 0.13.x. Does that make sense?
