### ISSUE TITLE
found a error when execute instruction "sbt run" or "sbt" -> "~re-start", on version 0.8.0

### ISSUE THREAD

**Issue by arccode** [spray/sbt-revolver#75]
when execute instruction "sbt run" or "sbt" -> "~re-start", found a exception(Error level), on version 0.8.0; but version 0.7.2 work fine.

----  [ERROR] : unable to found or load the main class net.arccode.boot.Boot ----

**Comment by jrudolph** [comment]
@arccode thanks for the report. That sounds as if there's no main class in your project if `run` *and* `reStart` both fail.

We'll need some kind of reproducer or more information to work on this.

**Comment by cooervo** [comment]
should be closed since OP didn't provided anymore details.

**Comment by arccode** [comment]
recently, I find this problem occur in windows 7 platform, and OSX is work fine.
