### ISSUE TITLE
Packaged sbt.compat not compatible with sbt-compat plugin

### ISSUE THREAD

**Issue by oleastre** [spray/sbt-revolver#79]
I cannot use sbt-revolver 0.9.0 with the latest ensime-sbt plugin ( same problem as https://github.com/ensime/ensime-sbt/issues/369 ).
sbt-ensime uses the sbt-compat plugin that packages it's objects in sbt.compat.
The latest jar of sbt-revolver also includes objects under the sbt/compta path that causes class loading issues.

Rebuilding the current sbt-revolver and testing with `sbt publishLocal` solves the problem. So I suppose it's some release/packaging problem.

**Comment by jrudolph** [comment]
Thanks for the report. Yes, makes sense to move the package to get rid of these kinds of problems.

**Comment by jrudolph** [comment]
Indeed, we just stumbled over the same issues ourselves (this time in combination with sbt-dependency-graph). It took a while until I remembered this issue. Great, you already figured out that it was related to those classes in the jar which shouldn't have been there. That was really unexpected.

I released v0.9.1 cleanly which should fix the issue.

**Comment by oleastre** [comment]
Thanks for that. 
Maybe using sbt-release for the release process should be a good option to avoid that kind of error. It ensure your git repository does not contain modifications and it starts the release with a "clean" command ;-)

**Comment by jrudolph** [comment]
Yeah, that's right. Every automated process would be good I guess. At some point we'll get to that ;)
