### ISSUE TITLE
Not working with SBT 1.0.3

### ISSUE THREAD

**Issue by gabfssilva** [spray/sbt-revolver#81]
No idea why, but, the plugin won't work with SBT 1.0.3. It just don't seem to listen to code changes.

Have anyone else experienced this issue?

**Comment by eddpeterson** [comment]
Same issue for me after upgrading to SBT 1.0.3.

**Comment by gabfssilva** [comment]
This seems a SBT 1.0.3 bug: sbt/sbt#3687

**Comment by gabfssilva** [comment]
Since this is not a plugin issue, I'm closing it.
