### ISSUE TITLE
BindException in akka-http  command: sbt "~ ; reStart ;run"

### ISSUE THREAD

**Issue by Min3953** [spray/sbt-revolver#84]
```
Bind failed for TCP channel on endpoint [/0.0.0.0:8082]
java.net.BindException: Address in use
```

`addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")`
`sbt.version=1.1.0`
`scala.version="2.12.4"`

**Comment by jrudolph** [comment]
Hi @Min3953, thanks for the report. The `reStart` task is a replacement for `run`, so don't execute both at the same time or the application will be started twice. That's what the error message says actually: "I wanted to start a server on port 8082 but another application has already occupied the port".

**Comment by Min3953** [comment]
Thank you for your answer!! I understand what I did wrong. I close it.
